### ISSUE TITLE
domain does not match the negotiation domain

### ISSUE THREAD

**Issue by zaneghost** [tdgunes/ExampleAgent#32]
My agent's negotiation will not return further information after the point of "Finished negotiation session in 3.6257" and console is returning 

java.lang.IllegalStateException: domain does not match the negotiation domain
	at negotiator.utility.UtilitySpaceTools.checkReadyForNegotiation(UtilitySpaceTools.java:98)
	at negotiator.analysis.MultilateralAnalysis.initializeUtilitySpaces(MultilateralAnalysis.java:288)
	at negotiator.analysis.MultilateralAnalysis.<init>(MultilateralAnalysis.java:78)
	at negotiator.logging.CsvLogger.logSingleSession(CsvLogger.java:251)
	at negotiator.gui.progress.session.ActionDocumentModel.notifyChange(ActionDocumentModel.java:51)
	at negotiator.gui.progress.session.ActionDocumentModel.notifyChange(ActionDocumentModel.java:1)
	at listener.DefaultListenable.notifyChange(DefaultListenable.java:29)
	at negotiator.session.SessionManager.runAndWait(SessionManager.java:136)
	at negotiator.session.SessionManager.run(SessionManager.java:107)
	at java.base/java.lang.Thread.run(Thread.java:844)

This will not happen if I comment out my change to a bid section (to be exact, the putvalue chunk of code). Anyone can help??

**Comment by tdgunes** [comment]
I sent you an email about this.
